<?php


/**
 * This class defines the structure of the 'tw_plugin_module' table.
 *
 *
 * This class was autogenerated by Propel 1.5.1 on:
 *
 * Fri Jun  4 01:21:49 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.twCorePlugin.lib.model.map
 */
class twPluginModuleTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.twCorePlugin.lib.model.map.twPluginModuleTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tw_plugin_module');
		$this->setPhpName('twPluginModule');
		$this->setClassname('twPluginModule');
		$this->setPackage('plugins.twCorePlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('PLUGIN_ID', 'PluginId', 'INTEGER', 'tw_plugin', 'ID', true, null, null);
		$this->addForeignKey('STATUS_ID', 'StatusId', 'INTEGER', 'tw_plugin_status', 'ID', true, null, null);
		$this->addColumn('ROUTE', 'Route', 'VARCHAR', true, 50, null);
		$this->addColumn('CREDENTIALS', 'Credentials', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CODE', 'Code', 'VARCHAR', true, 50, null);
		$this->addColumn('POS', 'Pos', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('twPlugin', 'twPlugin', RelationMap::MANY_TO_ONE, array('plugin_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('twPluginStatus', 'twPluginStatus', RelationMap::MANY_TO_ONE, array('status_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('twPluginModuleI18n', 'twPluginModuleI18n', RelationMap::ONE_TO_MANY, array('id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_i18n' => array('i18n_table' => 'tw_plugin_module_i18n', ),
		);
	} // getBehaviors()

} // twPluginModuleTableMap
