<?php

/**
 * Base class that represents a row from the 'tw_plugin_module' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1 on:
 *
 * Fri Jun  4 01:21:49 2010
 *
 * @package    propel.generator.plugins.twCorePlugin.lib.model.om
 */
abstract class BasetwPluginModule extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
  const PEER = 'twPluginModulePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        twPluginModulePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the plugin_id field.
	 * @var        int
	 */
	protected $plugin_id;

	/**
	 * The value for the status_id field.
	 * @var        int
	 */
	protected $status_id;

	/**
	 * The value for the route field.
	 * @var        string
	 */
	protected $route;

	/**
	 * The value for the credentials field.
	 * @var        string
	 */
	protected $credentials;

	/**
	 * The value for the code field.
	 * @var        string
	 */
	protected $code;

	/**
	 * The value for the pos field.
	 * @var        int
	 */
	protected $pos;

	/**
	 * @var        twPlugin
	 */
	protected $atwPlugin;

	/**
	 * @var        twPluginStatus
	 */
	protected $atwPluginStatus;

	/**
	 * @var        array twPluginModuleI18n[] Collection to store aggregation of twPluginModuleI18n objects.
	 */
	protected $colltwPluginModuleI18ns;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony_i18n behavior
	
	/**
	 * @var string The value for the culture field
	 */
	protected $culture = null;
	
	/**
	 * @var array Current I18N objects
	 */
	protected $current_i18n = array();

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [plugin_id] column value.
	 * 
	 * @return     int
	 */
	public function getPluginId()
	{
		return $this->plugin_id;
	}

	/**
	 * Get the [status_id] column value.
	 * 
	 * @return     int
	 */
	public function getStatusId()
	{
		return $this->status_id;
	}

	/**
	 * Get the [route] column value.
	 * 
	 * @return     string
	 */
	public function getRoute()
	{
		return $this->route;
	}

	/**
	 * Get the [credentials] column value.
	 * 
	 * @return     string
	 */
	public function getCredentials()
	{
		return $this->credentials;
	}

	/**
	 * Get the [code] column value.
	 * 
	 * @return     string
	 */
	public function getCode()
	{
		return $this->code;
	}

	/**
	 * Get the [pos] column value.
	 * 
	 * @return     int
	 */
	public function getPos()
	{
		return $this->pos;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     twPluginModule The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = twPluginModulePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [plugin_id] column.
	 * 
	 * @param      int $v new value
	 * @return     twPluginModule The current object (for fluent API support)
	 */
	public function setPluginId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->plugin_id !== $v) {
			$this->plugin_id = $v;
			$this->modifiedColumns[] = twPluginModulePeer::PLUGIN_ID;
		}

		if ($this->atwPlugin !== null && $this->atwPlugin->getId() !== $v) {
			$this->atwPlugin = null;
		}

		return $this;
	} // setPluginId()

	/**
	 * Set the value of [status_id] column.
	 * 
	 * @param      int $v new value
	 * @return     twPluginModule The current object (for fluent API support)
	 */
	public function setStatusId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status_id !== $v) {
			$this->status_id = $v;
			$this->modifiedColumns[] = twPluginModulePeer::STATUS_ID;
		}

		if ($this->atwPluginStatus !== null && $this->atwPluginStatus->getId() !== $v) {
			$this->atwPluginStatus = null;
		}

		return $this;
	} // setStatusId()

	/**
	 * Set the value of [route] column.
	 * 
	 * @param      string $v new value
	 * @return     twPluginModule The current object (for fluent API support)
	 */
	public function setRoute($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->route !== $v) {
			$this->route = $v;
			$this->modifiedColumns[] = twPluginModulePeer::ROUTE;
		}

		return $this;
	} // setRoute()

	/**
	 * Set the value of [credentials] column.
	 * 
	 * @param      string $v new value
	 * @return     twPluginModule The current object (for fluent API support)
	 */
	public function setCredentials($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->credentials !== $v) {
			$this->credentials = $v;
			$this->modifiedColumns[] = twPluginModulePeer::CREDENTIALS;
		}

		return $this;
	} // setCredentials()

	/**
	 * Set the value of [code] column.
	 * 
	 * @param      string $v new value
	 * @return     twPluginModule The current object (for fluent API support)
	 */
	public function setCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->code !== $v) {
			$this->code = $v;
			$this->modifiedColumns[] = twPluginModulePeer::CODE;
		}

		return $this;
	} // setCode()

	/**
	 * Set the value of [pos] column.
	 * 
	 * @param      int $v new value
	 * @return     twPluginModule The current object (for fluent API support)
	 */
	public function setPos($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pos !== $v) {
			$this->pos = $v;
			$this->modifiedColumns[] = twPluginModulePeer::POS;
		}

		return $this;
	} // setPos()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->plugin_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->status_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->route = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->credentials = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->code = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->pos = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 7; // 7 = twPluginModulePeer::NUM_COLUMNS - twPluginModulePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating twPluginModule object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->atwPlugin !== null && $this->plugin_id !== $this->atwPlugin->getId()) {
			$this->atwPlugin = null;
		}
		if ($this->atwPluginStatus !== null && $this->status_id !== $this->atwPluginStatus->getId()) {
			$this->atwPluginStatus = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(twPluginModulePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = twPluginModulePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->atwPlugin = null;
			$this->atwPluginStatus = null;
			$this->colltwPluginModuleI18ns = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(twPluginModulePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasetwPluginModule:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				twPluginModuleQuery::create()
					->filterByPrimaryKey($this->getPrimaryKey())
					->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasetwPluginModule:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(twPluginModulePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasetwPluginModule:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasetwPluginModule:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				twPluginModulePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->atwPlugin !== null) {
				if ($this->atwPlugin->isModified() || $this->atwPlugin->isNew()) {
					$affectedRows += $this->atwPlugin->save($con);
				}
				$this->settwPlugin($this->atwPlugin);
			}

			if ($this->atwPluginStatus !== null) {
				if ($this->atwPluginStatus->isModified() || $this->atwPluginStatus->isNew()) {
					$affectedRows += $this->atwPluginStatus->save($con);
				}
				$this->settwPluginStatus($this->atwPluginStatus);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = twPluginModulePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$criteria = $this->buildCriteria();
					if ($criteria->keyContainsValue(twPluginModulePeer::ID) ) {
						throw new PropelException('Cannot insert a value for auto-increment primary key ('.twPluginModulePeer::ID.')');
					}

					$pk = BasePeer::doInsert($criteria, $con);
					$affectedRows += 1;
					$this->setId($pk);  //[IMV] update autoincrement primary key
					$this->setNew(false);
				} else {
					$affectedRows += twPluginModulePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->colltwPluginModuleI18ns !== null) {
				foreach ($this->colltwPluginModuleI18ns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->atwPlugin !== null) {
				if (!$this->atwPlugin->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->atwPlugin->getValidationFailures());
				}
			}

			if ($this->atwPluginStatus !== null) {
				if (!$this->atwPluginStatus->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->atwPluginStatus->getValidationFailures());
				}
			}


			if (($retval = twPluginModulePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->colltwPluginModuleI18ns !== null) {
					foreach ($this->colltwPluginModuleI18ns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = twPluginModulePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPluginId();
				break;
			case 2:
				return $this->getStatusId();
				break;
			case 3:
				return $this->getRoute();
				break;
			case 4:
				return $this->getCredentials();
				break;
			case 5:
				return $this->getCode();
				break;
			case 6:
				return $this->getPos();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. 
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $includeForeignObjects = false)
	{
		$keys = twPluginModulePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPluginId(),
			$keys[2] => $this->getStatusId(),
			$keys[3] => $this->getRoute(),
			$keys[4] => $this->getCredentials(),
			$keys[5] => $this->getCode(),
			$keys[6] => $this->getPos(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->atwPlugin) {
				$result['twPlugin'] = $this->atwPlugin->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->atwPluginStatus) {
				$result['twPluginStatus'] = $this->atwPluginStatus->toArray($keyType, $includeLazyLoadColumns, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = twPluginModulePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPluginId($value);
				break;
			case 2:
				$this->setStatusId($value);
				break;
			case 3:
				$this->setRoute($value);
				break;
			case 4:
				$this->setCredentials($value);
				break;
			case 5:
				$this->setCode($value);
				break;
			case 6:
				$this->setPos($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = twPluginModulePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPluginId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setStatusId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setRoute($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCredentials($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCode($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPos($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(twPluginModulePeer::DATABASE_NAME);

		if ($this->isColumnModified(twPluginModulePeer::ID)) $criteria->add(twPluginModulePeer::ID, $this->id);
		if ($this->isColumnModified(twPluginModulePeer::PLUGIN_ID)) $criteria->add(twPluginModulePeer::PLUGIN_ID, $this->plugin_id);
		if ($this->isColumnModified(twPluginModulePeer::STATUS_ID)) $criteria->add(twPluginModulePeer::STATUS_ID, $this->status_id);
		if ($this->isColumnModified(twPluginModulePeer::ROUTE)) $criteria->add(twPluginModulePeer::ROUTE, $this->route);
		if ($this->isColumnModified(twPluginModulePeer::CREDENTIALS)) $criteria->add(twPluginModulePeer::CREDENTIALS, $this->credentials);
		if ($this->isColumnModified(twPluginModulePeer::CODE)) $criteria->add(twPluginModulePeer::CODE, $this->code);
		if ($this->isColumnModified(twPluginModulePeer::POS)) $criteria->add(twPluginModulePeer::POS, $this->pos);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(twPluginModulePeer::DATABASE_NAME);
		$criteria->add(twPluginModulePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of twPluginModule (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{
		$copyObj->setPluginId($this->plugin_id);
		$copyObj->setStatusId($this->status_id);
		$copyObj->setRoute($this->route);
		$copyObj->setCredentials($this->credentials);
		$copyObj->setCode($this->code);
		$copyObj->setPos($this->pos);

		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->gettwPluginModuleI18ns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addtwPluginModuleI18n($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);
		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     twPluginModule Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     twPluginModulePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new twPluginModulePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a twPlugin object.
	 *
	 * @param      twPlugin $v
	 * @return     twPluginModule The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function settwPlugin(twPlugin $v = null)
	{
		if ($v === null) {
			$this->setPluginId(NULL);
		} else {
			$this->setPluginId($v->getId());
		}

		$this->atwPlugin = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the twPlugin object, it will not be re-added.
		if ($v !== null) {
			$v->addtwPluginModule($this);
		}

		return $this;
	}


	/**
	 * Get the associated twPlugin object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     twPlugin The associated twPlugin object.
	 * @throws     PropelException
	 */
	public function gettwPlugin(PropelPDO $con = null)
	{
		if ($this->atwPlugin === null && ($this->plugin_id !== null)) {
			$this->atwPlugin = twPluginQuery::create()->findPk($this->plugin_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->atwPlugin->addtwPluginModules($this);
			 */
		}
		return $this->atwPlugin;
	}

	/**
	 * Declares an association between this object and a twPluginStatus object.
	 *
	 * @param      twPluginStatus $v
	 * @return     twPluginModule The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function settwPluginStatus(twPluginStatus $v = null)
	{
		if ($v === null) {
			$this->setStatusId(NULL);
		} else {
			$this->setStatusId($v->getId());
		}

		$this->atwPluginStatus = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the twPluginStatus object, it will not be re-added.
		if ($v !== null) {
			$v->addtwPluginModule($this);
		}

		return $this;
	}


	/**
	 * Get the associated twPluginStatus object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     twPluginStatus The associated twPluginStatus object.
	 * @throws     PropelException
	 */
	public function gettwPluginStatus(PropelPDO $con = null)
	{
		if ($this->atwPluginStatus === null && ($this->status_id !== null)) {
			$this->atwPluginStatus = twPluginStatusQuery::create()->findPk($this->status_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->atwPluginStatus->addtwPluginModules($this);
			 */
		}
		return $this->atwPluginStatus;
	}

	/**
	 * Clears out the colltwPluginModuleI18ns collection
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addtwPluginModuleI18ns()
	 */
	public function cleartwPluginModuleI18ns()
	{
		$this->colltwPluginModuleI18ns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the colltwPluginModuleI18ns collection.
	 *
	 * By default this just sets the colltwPluginModuleI18ns collection to an empty array (like clearcolltwPluginModuleI18ns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function inittwPluginModuleI18ns()
	{
		$this->colltwPluginModuleI18ns = new PropelObjectCollection();
		$this->colltwPluginModuleI18ns->setModel('twPluginModuleI18n');
	}

	/**
	 * Gets an array of twPluginModuleI18n objects which contain a foreign key that references this object.
	 *
	 * If the $criteria is not null, it is used to always fetch the results from the database.
	 * Otherwise the results are fetched from the database the first time, then cached.
	 * Next time the same method is called without $criteria, the cached collection is returned.
	 * If this twPluginModule is new, it will return
	 * an empty collection or the current collection; the criteria is ignored on a new object.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @return     PropelCollection|array twPluginModuleI18n[] List of twPluginModuleI18n objects
	 * @throws     PropelException
	 */
	public function gettwPluginModuleI18ns($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->colltwPluginModuleI18ns || null !== $criteria) {
			if ($this->isNew() && null === $this->colltwPluginModuleI18ns) {
				// return empty collection
				$this->inittwPluginModuleI18ns();
			} else {
				$colltwPluginModuleI18ns = twPluginModuleI18nQuery::create(null, $criteria)
					->filterBytwPluginModule($this)
					->find($con);
				if (null !== $criteria) {
					return $colltwPluginModuleI18ns;
				}
				$this->colltwPluginModuleI18ns = $colltwPluginModuleI18ns;
			}
		}
		return $this->colltwPluginModuleI18ns;
	}

	/**
	 * Returns the number of related twPluginModuleI18n objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related twPluginModuleI18n objects.
	 * @throws     PropelException
	 */
	public function counttwPluginModuleI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if(null === $this->colltwPluginModuleI18ns || null !== $criteria) {
			if ($this->isNew() && null === $this->colltwPluginModuleI18ns) {
				return 0;
			} else {
				$query = twPluginModuleI18nQuery::create(null, $criteria);
				if($distinct) {
					$query->distinct();
				}
				return $query
					->filterBytwPluginModule($this)
					->count($con);
			}
		} else {
			return count($this->colltwPluginModuleI18ns);
		}
	}

	/**
	 * Method called to associate a twPluginModuleI18n object to this object
	 * through the twPluginModuleI18n foreign key attribute.
	 *
	 * @param      twPluginModuleI18n $l twPluginModuleI18n
	 * @return     void
	 * @throws     PropelException
	 */
	public function addtwPluginModuleI18n(twPluginModuleI18n $l)
	{
		if ($this->colltwPluginModuleI18ns === null) {
			$this->inittwPluginModuleI18ns();
		}
		if (!$this->colltwPluginModuleI18ns->contains($l)) { // only add it if the **same** object is not already associated
			$this->colltwPluginModuleI18ns[]= $l;
			$l->settwPluginModule($this);
		}
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->plugin_id = null;
		$this->status_id = null;
		$this->route = null;
		$this->credentials = null;
		$this->code = null;
		$this->pos = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->colltwPluginModuleI18ns) {
				foreach ((array) $this->colltwPluginModuleI18ns as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->colltwPluginModuleI18ns = null;
		$this->atwPlugin = null;
		$this->atwPluginStatus = null;
	}

	// symfony_i18n behavior
	
	/**
	 * Returns the culture.
	 *
	 * @return string The culture
	 */
	public function getCulture()
	{
	  return $this->culture;
	}
	
	/**
	 * Sets the culture.
	 *
	 * @param string  The culture to set
	 *
	 * @return twPluginModule
	 */
	public function setCulture($culture)
	{
	  $this->culture = $culture;
	  return $this;
	}
	
	/**
	 * Returns the "name" value from the current {@link twPluginModuleI18n}.
	 */
	public function getName($culture = null)
	{
	  return $this->getCurrenttwPluginModuleI18n($culture)->getName();
	}
	
	/**
	 * Sets the "name" value of the current {@link twPluginModuleI18n}.
	 *
	 * @return twPluginModule
	 */
	public function setName($value, $culture = null)
	{
	  $this->getCurrenttwPluginModuleI18n($culture)->setName($value);
	  return $this;
	}
	
	/**
	 * Returns the "description" value from the current {@link twPluginModuleI18n}.
	 */
	public function getDescription($culture = null)
	{
	  return $this->getCurrenttwPluginModuleI18n($culture)->getDescription();
	}
	
	/**
	 * Sets the "description" value of the current {@link twPluginModuleI18n}.
	 *
	 * @return twPluginModule
	 */
	public function setDescription($value, $culture = null)
	{
	  $this->getCurrenttwPluginModuleI18n($culture)->setDescription($value);
	  return $this;
	}
	
	/**
	 * Returns the current translation.
	 *
	 * @return twPluginModuleI18n
	 */
	public function getCurrenttwPluginModuleI18n($culture = null)
	{
	  if (null === $culture)
	  {
	    $culture = null === $this->culture ? sfPropel::getDefaultCulture() : $this->culture;
	  }
	
	  if (!isset($this->current_i18n[$culture]))
	  {
	    $object = $this->isNew() ? null : twPluginModuleI18nPeer::retrieveByPK($this->getPrimaryKey(), $culture);
	    if ($object)
	    {
	      $this->settwPluginModuleI18nForCulture($object, $culture);
	    }
	    else
	    {
	      $this->settwPluginModuleI18nForCulture(new twPluginModuleI18n(), $culture);
	      $this->current_i18n[$culture]->setCulture($culture);
	    }
	  }
	
	  return $this->current_i18n[$culture];
	}
	
	/**
	 * Sets the translation object for a culture.
	 */
	public function settwPluginModuleI18nForCulture(twPluginModuleI18n $object, $culture)
	{
	  $this->current_i18n[$culture] = $object;
	  $this->addtwPluginModuleI18n($object);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BasetwPluginModule:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		if (preg_match('/get(\w+)/', $name, $matches) && $this->hasVirtualColumn($matches[1])) {
			return $this->getVirtualColumn($matches[1]);
		}
		throw new PropelException('Call to undefined method: ' . $name);
	}

} // BasetwPluginModule
