<?php


/**
 * Base class that represents a query for the 'tw_plugin_status' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1 on:
 *
 * Fri Jun  4 01:21:49 2010
 *
 * @method     twPluginStatusQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     twPluginStatusQuery orderByCode($order = Criteria::ASC) Order by the code column
 *
 * @method     twPluginStatusQuery groupById() Group by the id column
 * @method     twPluginStatusQuery groupByCode() Group by the code column
 *
 * @method     twPluginStatusQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     twPluginStatusQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     twPluginStatusQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     twPluginStatusQuery leftJointwPluginStatusI18n($relationAlias = '') Adds a LEFT JOIN clause to the query using the twPluginStatusI18n relation
 * @method     twPluginStatusQuery rightJointwPluginStatusI18n($relationAlias = '') Adds a RIGHT JOIN clause to the query using the twPluginStatusI18n relation
 * @method     twPluginStatusQuery innerJointwPluginStatusI18n($relationAlias = '') Adds a INNER JOIN clause to the query using the twPluginStatusI18n relation
 *
 * @method     twPluginStatusQuery leftJointwPlugin($relationAlias = '') Adds a LEFT JOIN clause to the query using the twPlugin relation
 * @method     twPluginStatusQuery rightJointwPlugin($relationAlias = '') Adds a RIGHT JOIN clause to the query using the twPlugin relation
 * @method     twPluginStatusQuery innerJointwPlugin($relationAlias = '') Adds a INNER JOIN clause to the query using the twPlugin relation
 *
 * @method     twPluginStatusQuery leftJointwPluginModule($relationAlias = '') Adds a LEFT JOIN clause to the query using the twPluginModule relation
 * @method     twPluginStatusQuery rightJointwPluginModule($relationAlias = '') Adds a RIGHT JOIN clause to the query using the twPluginModule relation
 * @method     twPluginStatusQuery innerJointwPluginModule($relationAlias = '') Adds a INNER JOIN clause to the query using the twPluginModule relation
 *
 * @method     twPluginStatus findOne(PropelPDO $con = null) Return the first twPluginStatus matching the query
 * @method     twPluginStatus findOneById(int $id) Return the first twPluginStatus filtered by the id column
 * @method     twPluginStatus findOneByCode(string $code) Return the first twPluginStatus filtered by the code column
 *
 * @method     array findById(int $id) Return twPluginStatus objects filtered by the id column
 * @method     array findByCode(string $code) Return twPluginStatus objects filtered by the code column
 *
 * @package    propel.generator.plugins.twCorePlugin.lib.model.om
 */
abstract class BasetwPluginStatusQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BasetwPluginStatusQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'twPluginStatus', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new twPluginStatusQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    twPluginStatusQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof twPluginStatusQuery) {
			return $criteria;
		}
		$query = new twPluginStatusQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    twPluginStatus|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = twPluginStatusPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(twPluginStatusPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(twPluginStatusPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(twPluginStatusPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the code column
	 * 
	 * @param     string $code The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function filterByCode($code = null, $comparison = null)
	{
		if (is_array($code)) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		} elseif (preg_match('/[\%\*]/', $code)) {
			$code = str_replace('*', '%', $code);
			if (null === $comparison) {
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(twPluginStatusPeer::CODE, $code, $comparison);
	}

	/**
	 * Filter the query by a related twPluginStatusI18n object
	 *
	 * @param     twPluginStatusI18n $twPluginStatusI18n  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function filterBytwPluginStatusI18n($twPluginStatusI18n, $comparison = null)
	{
		return $this
			->addUsingAlias(twPluginStatusPeer::ID, $twPluginStatusI18n->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the twPluginStatusI18n relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function jointwPluginStatusI18n($relationAlias = '', $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('twPluginStatusI18n');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'twPluginStatusI18n');
		}
		
		return $this;
	}

	/**
	 * Use the twPluginStatusI18n relation twPluginStatusI18n object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    twPluginStatusI18nQuery A secondary query class using the current class as primary query
	 */
	public function usetwPluginStatusI18nQuery($relationAlias = '', $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->jointwPluginStatusI18n($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'twPluginStatusI18n', 'twPluginStatusI18nQuery');
	}

	/**
	 * Filter the query by a related twPlugin object
	 *
	 * @param     twPlugin $twPlugin  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function filterBytwPlugin($twPlugin, $comparison = null)
	{
		return $this
			->addUsingAlias(twPluginStatusPeer::ID, $twPlugin->getStatusId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the twPlugin relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function jointwPlugin($relationAlias = '', $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('twPlugin');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'twPlugin');
		}
		
		return $this;
	}

	/**
	 * Use the twPlugin relation twPlugin object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    twPluginQuery A secondary query class using the current class as primary query
	 */
	public function usetwPluginQuery($relationAlias = '', $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->jointwPlugin($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'twPlugin', 'twPluginQuery');
	}

	/**
	 * Filter the query by a related twPluginModule object
	 *
	 * @param     twPluginModule $twPluginModule  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function filterBytwPluginModule($twPluginModule, $comparison = null)
	{
		return $this
			->addUsingAlias(twPluginStatusPeer::ID, $twPluginModule->getStatusId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the twPluginModule relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function jointwPluginModule($relationAlias = '', $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('twPluginModule');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'twPluginModule');
		}
		
		return $this;
	}

	/**
	 * Use the twPluginModule relation twPluginModule object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    twPluginModuleQuery A secondary query class using the current class as primary query
	 */
	public function usetwPluginModuleQuery($relationAlias = '', $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->jointwPluginModule($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'twPluginModule', 'twPluginModuleQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     twPluginStatus $twPluginStatus Object to remove from the list of results
	 *
	 * @return    twPluginStatusQuery The current query, for fluid interface
	 */
	public function prune($twPluginStatus = null)
	{
		if ($twPluginStatus) {
			$this->addUsingAlias(twPluginStatusPeer::ID, $twPluginStatus->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BasetwPluginStatusQuery
