generator:
  class: sfPropelGenerator
  param:
    model_class:           twPlugin
    theme:                 thunderwolf
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_plugin
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Plugin properties
        peer_method:   doSelectWithI18n
        display: [name, status]
        max_per_page: 10
      filter:
        display: [status_id, code]
      form:    ~
      edit:
        title: Plugin properties
      new:
        title: Plugin properties

