<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tw_plugin_status_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1 on:
 *
 * Wed May 12 23:26:28 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.twCorePlugin.lib.model
 */
class twPluginStatusI18nQuery extends BasetwPluginStatusI18nQuery {

} // twPluginStatusI18nQuery
