<?php



/**
 * Skeleton subclass for representing a row from the 'tw_routing' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Fri Sep  3 22:48:42 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.twCorePlugin.lib.model
 */
class twRouting extends BasetwRouting {

} // twRouting
