<?php



/**
 * Skeleton subclass for representing a row from the 'tw_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Fri Jun 10 00:31:30 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.twCorePlugin.lib.model
 */
class twUser extends BasetwUser {

} // twUser
