propel:
  _attributes:           { package: plugins.twCorePlugin.lib.model }
    
  tw_version:
    _attributes:         { phpName: twVersion }
    id:                  { type: integer, required: true, primaryKey: true, autoincrement: true }
    name:                { type: VARCHAR, size: '20', required: true }
    value:               { type: LONGVARCHAR, required: true }
    _uniques:            { code: [name] }
    
  tw_language:
    _attributes:         { phpName: twLanguage }
    id:                  { type: integer, required: true, primaryKey: true, autoincrement: true }
    code:                { type: VARCHAR, size: '5', required: true }
    name:                { type: VARCHAR, size: '30', required: true }
    _uniques:            { code: [code] }

  tw_plugin_status:
    _attributes:         { phpName: twPluginStatus, isI18N: true, i18nTable: tw_plugin_status_i18n }
    id:                  { type: integer, required: true, primaryKey: true, autoincrement: true }
    code:                { type: VARCHAR, size: '20', required: true }
    _uniques:            { code: [code] }
    
  tw_plugin_status_i18n:
    _attributes:         { phpName: twPluginStatusI18n }
    id:                  { type: integer, required: true, primaryKey: true, foreignTable: tw_plugin_status, foreignReference: id }
    culture:             { isCulture: true, type: varchar, size: 7, required: true, primaryKey: true }
    name:                { type: LONGVARCHAR, required: true }
    description:         { type: LONGVARCHAR }

  tw_plugin:
    _attributes:         { phpName: twPlugin, isI18N: true, i18nTable: tw_plugin_i18n }
    id:                  { type: integer, required: true, primaryKey: true, autoincrement: true }
    status_id:           { type: integer, required: true, foreignTable: tw_plugin_status, foreignReference: id, onDelete: cascade }
    code:                { type: VARCHAR, size: '20', required: true }
    pos:                 { type: integer, required: true }
    _indexes:            { position: [pos] }
    _uniques:            { code: [code] }
    
  tw_plugin_i18n:
    _attributes:         { phpName: twPluginI18n }
    id:                  { type: integer, required: true, primaryKey: true, foreignTable: tw_plugin, foreignReference: id }
    culture:             { isCulture: true, type: varchar, size: 7, required: true, primaryKey: true }
    name:                { type: LONGVARCHAR, required: true }
    description:         { type: LONGVARCHAR }

  tw_plugin_module:
    _attributes:         { phpName: twPluginModule, isI18N: true, i18nTable: tw_plugin_module_i18n }
    id:                  { type: integer, required: true, primaryKey: true, autoincrement: true }
    plugin_id:           { type: integer, required: true, foreignTable: tw_plugin, foreignReference: id, onDelete: cascade }
    status_id:           { type: integer, required: true, foreignTable: tw_plugin_status, foreignReference: id, onDelete: cascade }
    route:               { type: VARCHAR, size: '50', required: true }
    credentials:         { type: LONGVARCHAR, required: false }
    code:                { type: VARCHAR, size: '50', required: true }
    pos:                 { type: integer, required: true }
    _indexes:            { position: [pos] }
    _uniques:            { code: [code] }

  tw_plugin_module_i18n:
    _attributes:         { phpName: twPluginModuleI18n }
    id:                  { type: integer, required: true, primaryKey: true, foreignTable: tw_plugin_module, foreignReference: id }
    culture:             { isCulture: true, type: varchar, size: 7, required: true, primaryKey: true }
    name:                { type: VARCHAR, size: '50', required: true }
    description:         { type: LONGVARCHAR }
    
  tw_settings: 
    _attributes:    { phpName: twSettings }
    name:    { type: VARCHAR, size: '250', required: true }
    value:    { type: LONGVARCHAR, required: false }
    _uniques:
      uname: [name]
